plugins:
  - jekyll-seo-tag

social:
  name: A510
  links:
    - https://www.facebook.com/a510ru
    - https://www.instagram.com/a510ru

logo: /images/logo.png
url: https://interiors.a510.ru

title: ""
lang: "ru_RU"

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/logo.png
